#!/bin/bash
fswatch *.tex | {
    while read x; do  
        errorfile=${x%%.tex}.errors
        syncfile=${x%%.tex}.synctex.gz
        if latexrun --latex-args="-synctex=1" $x > latex.out/$errorfile
        then   # no error code, so compiling completed
            if [ -f latex.out/$syncfile ]
            then
                cp latex.out/$syncfile $syncfile
            fi
            killall -HUP mupdf
        fi
        cat latex.out/$errorfile
    done
}
    #rubber --warn all -m pdftex --inplace --maxerr -1 --short &&\
