#!/bin/bash
fswatch *.tex | {
    while read x; do
        filename="${x##*/}"
        errorfile="${filename%%.tex}.errors"
        syncfile="${filename%%.tex}.synctex.gz"
        mkdir -p latex.out
        echo "Building $filename"
        if latexrun --latex-args="-synctex=1" "$x" > "latex.out/$errorfile"
        then   # no error code, so compiling completed
            if [ -f "latex.out/$syncfile" ]
            then
                cp "latex.out/$syncfile" "$syncfile"
            fi
            killall -HUP mupdf
        fi
        cat "latex.out/$errorfile"
    done
}
